<?php

namespace Database\Seeders;

use App\Models\VehicleName;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehicleNameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        VehicleName::insert([
            ['name' => 'Honda Civic'],
            ['name' => 'Toyota Corolla'],
            ['name' => 'Tesla Model 3'],
            ['name' => 'Ford Mustang'],
            ['name' => 'Chevrolet Malibu'],
            ['name' => 'BMW 3 Series'],
            ['name' => 'Mercedes-Benz C-Class'],
            ['name' => 'Hyundai Elantra'],
            ['name' => 'Mazda 3'],
            ['name' => 'Audi A4'],
            ['name' => 'Honda Vario'],
            ['name' => 'Yamaha NMAX'],
            ['name' => 'Suzuki Satria F150'],
            ['name' => 'Kawasaki Ninja 250'],
            ['name' => 'Honda PCX'],
            ['name' => 'Yamaha Aerox'],
            ['name' => 'Vespa Primavera'],
            ['name' => 'Royal Enfield Classic 350'],
            ['name' => 'Ducati Monster 797'],
            ['name' => 'KTM Duke 200'],
            ['name' => 'Nissan Altima'],
            ['name' => 'Subaru Impreza'],
            ['name' => 'Lexus IS 300'],
            ['name' => 'Infiniti Q50'],
            ['name' => 'Volkswagen Passat'],
            ['name' => 'Chrysler 300'],
            ['name' => 'Acura TLX'],
            ['name' => 'Genesis G70'],
            ['name' => 'Jaguar XE'],
            ['name' => 'Volvo S60'],
            ['name' => 'Peugeot 508'],
            ['name' => 'Renault Megane'],
            ['name' => 'Skoda Octavia'],
            ['name' => 'Citroen C4'],
            ['name' => 'Mitsubishi Lancer'],
            ['name' => 'Fiat Tipo'],
            ['name' => 'Seat Leon'],
            ['name' => 'Opel Astra'],
            ['name' => 'Holden Commodore'],
            ['name' => 'Alfa Romeo Giulia'],
            ['name' => 'Honda Accord'],
            ['name' => 'Toyota Camry'],
            ['name' => 'Tesla Model S'],
            ['name' => 'Ford Fusion'],
            ['name' => 'Chevrolet Impala'],
            ['name' => 'BMW 5 Series'],
            ['name' => 'Mercedes-Benz E-Class'],
            ['name' => 'Hyundai Sonata'],
            ['name' => 'Mazda 6'],
            ['name' => 'Audi A6'],
            ['name' => 'Honda Beat'],
            ['name' => 'Yamaha Mio'],
            ['name' => 'Suzuki Address'],
            ['name' => 'Kawasaki KLX 150'],
            ['name' => 'Honda CBR500R'],
            ['name' => 'Yamaha R25'],
            ['name' => 'Vespa Sprint'],
            ['name' => 'Royal Enfield Meteor 350'],
            ['name' => 'Ducati Scrambler'],
            ['name' => 'KTM RC 390'],
            ['name' => 'Nissan Sentra'],
            ['name' => 'Subaru Legacy'],
            ['name' => 'Lexus ES 350'],
            ['name' => 'Infiniti Q70'],
            ['name' => 'Volkswagen Jetta'],
            ['name' => 'Chrysler Sebring'],
            ['name' => 'Acura RLX'],
            ['name' => 'Genesis G80'],
            ['name' => 'Jaguar XF'],
            ['name' => 'Volvo S90'],
            ['name' => 'Peugeot 3008'],
            ['name' => 'Renault Koleos'],
            ['name' => 'Skoda Superb'],
            ['name' => 'Citroen C5'],
            ['name' => 'Mitsubishi Outlander'],
            ['name' => 'Fiat 500X'],
            ['name' => 'Seat Ateca'],
            ['name' => 'Opel Insignia'],
            ['name' => 'Holden Calais'],
            ['name' => 'Alfa Romeo Stelvio'],
            ['name' => 'Honda CR-V'],
            ['name' => 'Toyota RAV4'],
            ['name' => 'Tesla Model X'],
            ['name' => 'Ford Escape'],
            ['name' => 'Chevrolet Equinox'],
            ['name' => 'BMW X3'],
            ['name' => 'Mercedes-Benz GLC'],
            ['name' => 'Hyundai Tucson'],
            ['name' => 'Mazda CX-5'],
            ['name' => 'Audi Q5'],
            ['name' => 'Honda Scoopy'],
            ['name' => 'Yamaha XMAX'],
            ['name' => 'Suzuki Burgman'],
            ['name' => 'Kawasaki Z250'],
            ['name' => 'Honda ADV 150'],
            ['name' => 'Yamaha Lexi'],
            ['name' => 'Vespa GTS'],
            ['name' => 'Royal Enfield Himalayan'],
            ['name' => 'Ducati Panigale V2'],
            ['name' => 'KTM 1290 Super Duke'],
]);
    }
}
